1:
  training_session: false
  predefined_training: 12_trials.csv
  training_accuracy: null
  training_attempts: null
  session_type: Predefined test
  predefined_test: test_44_items.csv
  randomize_trials_order: false
  randomize_graphs: false
  no_of_edges:
    '3': true
    '4': false
    '5': false
  crossed_edges:
    graphs_with_crossed: false
    graphs_without_crossed_edges: true
  types_of_target_vertices:
    direct: true
    indirect: true
  trials_per_cell: null
  n_of_trials: null
  break_after_n_trials: 0
2:
  one_target: false
  left_button_color: '#ffff00'
  right_button_color: '#0000ff'
  click_show_time: false
  trial_time: 24.0
  break_time: 1.0
  show_trial_number: true
  trial_number_position_x: 600
  trial_number_position_y: 350
  trial_number_size: 40
  show_mouse_buttons: true
  mouse_buttons_position_x: 0
  mouse_buttons_position_y: -250
  mouse_buttons_size: 100
  show_clock_icon: true
  clock_position_x: 0
  clock_position_y: 200
  clock_size: 100
  clock_time: 4.0
3:
  feedback: true
  correct_answer: Your answer was correct
  correct_answer_color: '#008000'
  incorrect_answer: Your answer was incorrect. The correct answer is presented above.
  incorrect_answer_color: '#ff0000'
  no_answer: No answer. The correct answer is presented above.
  no_answer_color: '#000000'
  press_space_message: Press space
  press_space_button_color: '#000000'
  feedback_text_size: 20
  feedback_position:
  - 0
  - -100
4:
  text_color: '#000000'
  background_color: '#dddddd'
  text_size: 20
  vertices_color: '#000000'
  edges_color: '#000000'
  left_graph_position:
  - -130
  - 0
  right_graph_position:
  - 130
  - 0
  vertices_size: 18
  vertices_distance: 80
  gap_between_edges_and_vertices: 21
  arrowhead_length: 14
  arrowhead_width: 7
