1:
  training_session: true
  predefined_training: 8_trials.csv
  training_accuracy: 0.5
  training_attempts: 4
  session_type: Randomized experiment
  predefined_test: test_44_trials.csv
  randomize_trials_order: true
  randomize_graphs: true
  no_of_edges:
    '3': true
    '4': true
    '5': false
  crossed_edges:
    graphs_with_crossed: true
    graphs_without_crossed_edges: true
  types_of_target_vertices:
    direct: true
    indirect: true
  trials_per_cell: 12
  n_of_trials: '96'
  break_after_n_trials: 4
2:
  one_target: false
  left_button_color: '#ffff00'
  right_button_color: '#0000ff'
  trial_time: 20.0
  break_time: 1.0
  click_show_time: 0.5
  show_trial_number: true
  trial_number_position_x: 11
  trial_number_position_y: 1
  trial_number_size: 1
  show_mouse_buttons: true
  mouse_buttons_position_x: 11
  mouse_buttons_position_y: 1
  mouse_buttons_size: 1
  show_clock_icon: true
  clock_position_x: 1
  clock_position_y: 1
  clock_size: 1
  clock_time: 1.0
3:
  feedback: true
  correct_answer: aa
  correct_answer_color: '#008000'
  incorrect_answer: bb
  incorrect_answer_color: '#ff0000'
  no_answer: cc
  no_answer_color: '#000000'
  press_space_message: dd
  press_space_button_color: '#c3063c'
  feedback_text_size: 33
  feedback_position:
  - '33'
  - '33'
4:
  text_color: '#000000'
  background_color: '#c0c0c0'
  text_size: 10
  vertices_color: '#000000'
  edges_color: '#000000'
  left_graph_position:
  - 10
  - 0
  right_graph_position:
  - 10
  - 0
  vertices_size: 10
  vertices_distance: 10
  gap_between_edges_and_vertices: 10
  arrowhead_length: 10
  arrowhead_width: 10
